### ISSUE TITLE
我有数问，请诸位静听 (對口相聲)

### ISSUE THREAD

**Issue by deadlineOvO** [RimoChan/Lunatic_red_eyes#1]
首先图是哪来的

**Comment by RimoChan** [comment]
當然是實際使用效果啦(笑)！
(其實是SAIGA堂的本子)

**Comment by deadlineOvO** [comment]
话说这玩意有受试者吗？

**Comment by RimoChan** [comment]
你看到 [![](https://img.shields.io/github/stars/RimoChan/Lunatic_red_eyes.svg)](https://github.com/RimoChan/Lunatic_red_eyes/stargazers) 了嗎？
要不是被催眠了，誰會來star這玩意……

**Comment by deadlineOvO** [comment]
如果他们只是点了然而没用过呢……

**Comment by RimoChan** [comment]
我的意思是「正常人肯定不會來star，所以點了star的肯定是已經被催眠的人」

**Comment by deadlineOvO** [comment]
怎么证明这点呢？

**Comment by RimoChan** [comment]
因爲 ![](https://img.shields.io/github/stars/RimoChan/Lunatic_red_eyes.svg) 充滿了強大的星之力量。普通的github用戶如果加星的話，就會因爲力量超載而喪失理智，但是被催眠的用戶只會根據催眠app行動所以沒有關係。

**Comment by deadlineOvO** [comment]
我有权怀疑你这句话是在骗我手里的 sata ？

**Comment by RimoChan** [comment]
隔壁的 [Librian](https://github.com/RimoChan/Librian) 的星之力量要弱一些，star那個可以獲得一些安全的星之力量……

**Comment by deadlineOvO** [comment]
所以星之力量怎么用？~~然后你就顺路推销了你的项目？~~

**Comment by RimoChan** [comment]
編程的時候會用到。星之力量越多，bug就越少。

**Comment by deadlineOvO** [comment]
怎么用呢？

**Comment by RimoChan** [comment]
不不不，這個星之力量是被動的，只要寫程序就會使用。
寫完以後傳github，力量的大小就會反映在星圖上。

**Comment by deadlineOvO** [comment]
我感觉你在糊弄我？？？

**Comment by RimoChan** [comment]
你的想象力不夠，需要多寫點輕小說鍛鍊一下——書名就叫《歡迎光臨「☆」Hub！》，設定就是在☆Hub裏給別人的項目加☆獲得☆power，☆power會提升你的code能量，對方的項目含有的code能量越多，加☆的人提升的☆power也越多。嗯，感覺很魔法。

**Comment by deadlineOvO** [comment]
然而我文理两爆炸怎么办啊

**Comment by RimoChan** [comment]
所以說要鍛鍊呀，編程能力和文采都是鍛鍊出來的，沒有人天生就會編程和寫小說的。

**Comment by deadlineOvO** [comment]
那我怎么锻炼啊？

**Comment by RimoChan** [comment]
我肯定是不會推薦你「多看多寫」這一類的胡話……

應當看寫小說的課本，然後，做課後習題。

**Comment by deadlineOvO** [comment]
然而我不上学了

**Comment by RimoChan** [comment]
學不學習和上不上學沒什麼關係。學無止境，不上學不是不學，而是讓你用更適合自己的方法學習。
只要你想鍛鍊，課本的pdf之類的都能找到。

**Comment by deadlineOvO** [comment]
虽然说是这回事，不过为啥感觉跑题了？

**Comment by RimoChan** [comment]
不如給這個issue標題加上「對口相聲」！

**Comment by deadlineOvO** [comment]
随便你了啊~~然而我的问题并没有被解决~~

**Comment by deadlineOvO** [comment]
等一下，我的问题还没有被解决啊

**Comment by RimoChan** [comment]
嗯？
我又倒回去看了一遍，感覺我都回答了啊？

**Comment by deadlineOvO** [comment]
然而我有一个问的问题仍然没有答案

**Comment by deadlineOvO** [comment]
怎么证明在这个项目点了 star 的亻被催眠了

如果是被催眠了，那么是被谁催眠了？

**Comment by RimoChan** [comment]
(還好問題不是「为啥感觉跑题了」，這個我還真沒法回答。)

所以說我證過了……上面的逆否命題不就是我證的嗎。

但是沒法知道是被誰催眠的，因爲這個證明顯然有漏洞——沒有證明是Lunatic_red_eyes催眠的，也就不能確認上層的「受试者」。

**Comment by deadlineOvO** [comment]
所以我点了这个项目的 star 我就丧失理智了是吗？

**Comment by RimoChan** [comment]
很有可能。你要star試一下。
不過可能你已經被催眠了，但是你自己還不知道，那樣的話就沒有問題。

**Comment by deadlineOvO** [comment]
那我怎么知道我自己被催眠了？

**Comment by RimoChan** [comment]
不都說了嘛……你加☆試一下，沒出問題就說明被催眠了。

**Comment by deadlineOvO** [comment]
那如果我没出问题我就一定被催眠了吗？

**Comment by RimoChan** [comment]
從廣義的催眠來看，的確是這麼回事。

因爲類似的方法有很多。比如，你可能中了隔壁的[深度圖像隱寫術](https://github.com/RimoChan/false_moon)……

**Comment by deadlineOvO** [comment]
你这个鬼话有几个人信啊？

**Comment by deadlineOvO** [comment]
……

那么

隔壁是怎么做到催眠的？

**Comment by RimoChan** [comment]
隔壁的readme裏不是寫了原理嘛……

**Comment by deadlineOvO** [comment]
问题是你都说了是你自己逗自己啊？

**Comment by RimoChan** [comment]
等等，這樣的問題應該發到隔壁的issue區啊。

**Comment by deadlineOvO** [comment]
但是我探讨的是那玩意是怎么催眠的啊

**Comment by deadlineOvO** [comment]
看来这个问题无法回答

**Comment by deadlineOvO** [comment]
人呢？是被自己写的东西催眠了吗？？

**Comment by deadlineOvO** [comment]
然后呢
